In [2]:
from pathlib import Path
import pandas as pd
import numpy as np
from scipy.stats import mode
from Bio.Seq import Seq
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord

In [3]:
ROOT = Path().cwd()
DATA = Path("../data")
CLADE_FASTA = DATA / "multifasta_for_clades"
ALIGNMENTS = DATA / "alignments"

In [10]:
to_fasta = ALIGNMENTS / "clade_1_merge_align.fasta"
seq_records = [seq_record for seq_record in SeqIO.parse(to_fasta, "fasta")]
len(seq_records)

20

In [279]:
%%time
align_crie_np = []
to_fasta = ALIGNMENTS / "clade_1_merge_align.fasta"
for seq_record in SeqIO.parse(to_fasta, "fasta"):
    align_crie_np.append(np.frombuffer(seq_record.seq.encode('utf-8'), dtype=np.int8))
align_crie_np = np.stack(align_crie_np)

CPU times: user 30.6 ms, sys: 7.19 ms, total: 37.8 ms
Wall time: 35.7 ms


In [280]:
align_crie_np

array([[103, 103,  99, ..., 103, 103, 103],
       [103, 103,  99, ..., 103, 103,  45],
       [103, 103,  99, ...,  45,  45,  45],
       ...,
       [ 97, 103, 103, ..., 103, 103,  45],
       [103, 103,  99, ..., 103, 103,  45],
       [103, 103,  99, ..., 103, 103,  45]], dtype=int8)

In [251]:
align_crie_np.shape

(20, 127611)

In [247]:
align_crie_np.max()

121

In [258]:
consensus_np = mode(align_crie_np[1:], axis=0, keepdims=False)

In [259]:
consensus_np.mode

array([103, 103,  99, ..., 103, 103,  45], dtype=int8)

In [ ]:
a.mode.shape

(127611,)

In [ ]:
a.mode * 2

array([-50, -50, -58, ..., -50, -50,  90], dtype=int8)

In [ ]:
b = mode(align_crie_np, axis=0, keepdims=True)

In [ ]:
b.mode.shape

(1, 127611)

In [ ]:
b.mode * 2

array([[-50, -50, -58, ..., -50, -50,  90]], dtype=int8)

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [270]:
consensus = Seq(consensus_np.mode.tobytes().decode("utf-8"))

In [ ]:
mask = np.isin(align_crie_np[0], np.frombuffer("-".encode('utf-8'), dtype=np.int8))
mask

array([False, False, False, ..., False, False, False])

In [ ]:
mask.sum()

2790

In [ ]:
align_crie_np[:, mask].shape

(20, 2790)